server {
    listen 80;
    server_name _;
    resolver 10.43.0.10 valid=30s ipv6=off;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        set $vpce_host "vpce-0c4b7f94c053837e6-9xr7gbx2.execute-api.eu-central-1.vpce.amazonaws.com";
        rewrite ^/api/(.*)$ /prod/$1 break;
        proxy_pass https://$vpce_host;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
        proxy_set_header Host "zup16ngei9.execute-api.eu-central-1.amazonaws.com";
        proxy_set_header x-apigw-api-id "zup16ngei9";
    }
}
