name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    name: Terraform validate + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Format check
        run: terraform fmt -check -recursive
      - name: Init (no backend)
        run: terraform init -backend=false
      - name: Validate
        run: terraform validate

  lambda:
    name: Lambda lint + syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install flake8
        run: pip install flake8
      - name: Compile + lint
        run: |
          python -m py_compile lambda/handler.py
          flake8 lambda/handler.py --max-line-length=120 --extend-ignore=E501,W503

  manifests:
    name: Kubernetes manifests validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
      - name: Validate manifests
        run: kubeconform -strict -ignore-missing-schemas -summary k8s/

  security:
    name: Security scan (Checkov)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: true